#!/bin/bash
printf "\n"
printf "====================================\n"
printf "Evaluating post-commit rules...\n"
printf "====================================\n"
printf "\n"

# generate list of committed files
files=$(git diff --name-only HEAD^ HEAD | xargs -0)
files_arr=($(echo "$files" | tr '\n' '\n'))

# iterate through list of secrets in secrets.json
secrets=$(cat secrets.json | jq -c '.secrets')
for secret in $(echo "${secrets}" | jq -r '.[] | @base64'); do
    _jq() {
     echo ${secret} | base64 --decode | jq -r ${1}
    }
    secret_msg=$(_jq '.msg')
    secret_hash=$(_jq '.id')
    # scan each staged file for usages of hash
    for file in "${files_arr[@]}"; do
        echo "Checking [$file] for [$secret_hash]"
        # replace found hash with secret
        sed -i '' "s/$secret_hash/$secret_msg/g" $file

        printf "Contents of [$file] after post-commit:\n"
        printf "%s" "$(<$file)\n"
    done
done

printf "====================================\n"
printf "\n"